language: node_js
node_js:
  - "10"

env:
  global:
    secure: "X1CXlb1X02VKjuRzqp7xdQLyJqy9oO25JfeRLKyD9uNsfunvuxmtHIaabpN/BJYcb/pnzKVEXvhkrjFLuwBwqptF7a70Y8zmx0UMT9b9BJwNacMdd/39ZgNpPAmo33mqufbdqmL3wc816puoqbYcoHGqA89rNDPRtVDoQf2eYMjk2sfExFuN30KFXDlKjhfNSKRjO3QEbYM6GAWB8HzdKQmFo+UarkXTjal1s0QHoS7VOOckHvgHRpIozO8wr5GJ3pK82JZ55fKuWwFWoFiRs36Pq5MBcboZ6bu4mnAt3VkFPNHn5TZkoJwaauG6jS+kj/18BL+o+CnWDW/yt1cS75zfIvHTJyAo7V0zXC7wdyHyxJLi1U88W3e0b7mH3lvCs01nI97YhCBNq7W/eqtwxjefJrnW2d5HetsLmQahkRS/EaU8etP7aTvK/5au7xGarncEf9mRiJ//DMjBASmUFhwD6VM7TyVkb2Aux+I/53DPA9yWXnPYTE5ia3TkiTzVTegNWIYP5JC8V2tctxsRx15y5NGN2FKmHGdZWzNUOo4iaUGj0qzKNeSZJfU/gTzJOldal12kX7MvOA6GZBhWfEB0CnmLvQqpJeljcWraw/42SeSlEzgIBg+k7+en95+QCog1+8BZXbgB5a+2pwfxQKhoULnUx4jaoUv2gEnVcuw="

before_install:
  - openssl aes-256-cbc -K $encrypted_33c2a12ca10a_key -iv $encrypted_33c2a12ca10a_iv -in .travis/secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
# before_script:
#   - npm run build

cache:
  directories:
    - node_modules

# addons:
#   ssh_known_hosts: ${HOST}
before_script:
  - echo -e "Host ${HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 travis_deploy.pem # this key should have push access
  - ssh-add travis_deploy.pem
  - rsync -r --delete-after --quiet . root@${HOST}:/root/globalchat-expressjs/
